from tkinter import *
master= Tk()
var1=IntVar()
Checkbutton(master,text='male',variable=var1).grid(row=0,sticky=W)
var2 = IntVar()
Checkbutton(master,text='female',variable=var2).grid(row=1,sticky=W)
var3 = IntVar()
Checkbutton(master,text='hi',variable=var3).grid(row=2,sticky=W)
var4 = IntVar()
Checkbutton(master,text='hello',variable=var4).grid(row=3,sticky=W)
mainloop()