#write a py program to create a mobile class and perform instanciation for 10 objects
class Mobile():
    def __init__(self):
        print("Mobile Class Constructor has been Created...!")
M1=Mobile()
M2=Mobile()
M3=Mobile()
M4=Mobile()
M5=Mobile()
M6=Mobile()
M7=Mobile()
M8=Mobile()
M9=Mobile()
M10=Mobile()
print(id(M1))
print(type(M1))  
print(id(M2))
print(type(M2)) 
print(id(M3))
print(type(M3))  
print(id(M4))
print(type(M4)) 
print(id(M5))
print(type(M5))
print(id(M6))
print(type(M6))
print(id(M7))
print(type(M7))
print(id(M8))
print(type(M8))
print(id(M9))
print(type(M9))
print(id(M10))
print(type(M10))
